@startuml Register Sequence

actor "Client" as client
participant "Money Tracker Go" as server
database "MySQL" as db

client --> server : POST /api/register
server --> server : validate input
note right
  1. email must be valid email format
  2. phone must starts with non zero number 
  (assumed country code)
  3. dob must be yyyy-mm-dd format
  4. username must be alphanumeric 
  between 3-30 characters
  5. password must be alphanumeric/special 
  characters with no whitespace 
  between 8-30 characters
  6. password can't be commonly used password 
  (bloom filter implemented)
end note
alt input is invalid
  server --> client : error response
end
server --> db : get user based on email, password, username request
db --> server : user data response 
alt user exists
  server --> client : conflict response
end
server --> server : hash password
server --> server : construct user data
server --> db : insert user
db --> server : success response
server --> server : generate jwt
server --> client : success response

@enduml