@startuml Create Transaction

actor "Client" as client
participant "Money Tracker Go" as server
database "MySQL" as db
database "Redis" as redis

client --> server : POST /api/transactions
server --> server : validate input
note right
  1. transaction type can only 
  be income or expense
  2. trx_date must 
  be in YYYY-MM-DD format
end note
alt input is invalid
  server --> client : error response
end
server --> server : construct create transaction data
server --> db : insert transaction to db
db --> server : query success response
server --> redis : HDEL income and expense transaction \nsummary based on user and period
redis --> server : OK response
server --> client : success response with data

@enduml