@startuml Delete Transaction

actor "Client" as client
participant "Money Tracker Go" as server
database "MySQL" as db

client --> server : DELETE /api/transactions/:id
server --> server : validate input
server --> db : get transaction by user and id
db --> server : transaction data response
alt transaction is null
  server --> client : not found response
end
server --> db : soft delete transaction from db
db --> server : query success response
server --> client : no content response

@enduml