@startuml Get Transaction Categories

actor "Client" as client
participant "Money Tracker Go" as server
database "MySQL" as db

client --> server : GET /api/transactions/categories
server --> server : validate query param
note right
  transaction type can only be income or expense
end note
alt query param is invalid
  server --> client : error response
end
server --> db : get all transaction categories by type
db --> server : transaction categories data response
server --> client : success response with data

@enduml